# Generated by Django 3.1.7 on 2021-04-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cedula',
            field=models.CharField(max_length=50, null=True, verbose_name='loquesea'),
        ),
    ]
