# Generated by Django 3.1.7 on 2021-04-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0003_profile_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cedula',
            field=models.CharField(max_length=50, null=True, verbose_name='Cedula'),
        ),
    ]
