# Generated by Django 3.1.7 on 2021-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0004_auto_20210401_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='mes',
            field=models.IntegerField(null=True, verbose_name='Mes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pago',
            field=models.IntegerField(null=True, verbose_name='pago bolivares'),
        ),
    ]
