# Generated by Django 3.1.7 on 2021-04-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0005_auto_20210401_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pago',
        ),
        migrations.AddField(
            model_name='post',
            name='mes_pay',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='monto_pago',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='firts_apellido',
            field=models.CharField(max_length=50, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AddField(
            model_name='profile',
            name='firts_nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Primer Nombre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nu_casa',
            field=models.CharField(max_length=50, null=True, verbose_name='Nº casa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_apellido',
            field=models.CharField(max_length=50, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
