# Generated by Django 3.1.7 on 2021-04-01 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('villapp', '0007_auto_20210401_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=50, verbose_name='Año de pago')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villapp.profile', verbose_name='Numero de Casa')),
                ('mes_enero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villapp.post', verbose_name='mes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
