# Generated by Django 3.1.7 on 2021-04-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0009_auto_20210401_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
