# Generated by Django 3.1.7 on 2021-04-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0010_recibo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recibo',
        ),
    ]
