# Generated by Django 3.1.7 on 2021-04-02 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('villapp', '0011_delete_recibo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='mes_pay',
        ),
        migrations.RemoveField(
            model_name='post',
            name='monto_pago',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firts_apellido',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firts_nombre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nu_casa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_apellido',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_nombre',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['from_user', 'to_user'], name='villapp_rel_from_us_1391ba_idx'),
        ),
    ]
