# Generated by Django 3.1.7 on 2021-04-02 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('villapp', '0013_auto_20210402_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasadelmes',
            name='Tabla',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
