# Generated by Django 3.1.7 on 2021-04-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0014_auto_20210402_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Monto',
        ),
    ]
