# Generated by Django 3.1.7 on 2021-04-02 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('villapp', '0015_remove_profile_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='nombreD',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
