# Generated by Django 3.1.7 on 2021-04-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0017_remove_deudas_tabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='villapp.tasadelmes'),
        ),
        migrations.AlterField(
            model_name='tasadelmes',
            name='Tabla',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
