# Generated by Django 3.1.7 on 2021-04-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0020_auto_20210402_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deudas',
            old_name='table',
            new_name='Tabla',
        ),
    ]
