# Generated by Django 3.1.7 on 2021-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0021_auto_20210402_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='deuda',
            field=models.IntegerField(null=True),
        ),
    ]
