# Generated by Django 3.1.7 on 2021-04-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0024_auto_20210402_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cedula',
        ),
    ]
