# Generated by Django 3.1.7 on 2021-04-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0026_remove_deudas_deuda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deudas',
            old_name='Tabla',
            new_name='Tabla_año',
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeAbril',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeAgosto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeDiciembre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeEnero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeFebrero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeJulio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeJunio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeMarzo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeMayo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeNoviembre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeOctubre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='PagodeSeptiembre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='pagototal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tasadelmes',
            name='PagoPromedio',
            field=models.IntegerField(null=True),
        ),
    ]
