# Generated by Django 3.1.7 on 2021-04-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0027_auto_20210403_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='pagototal',
        ),
    ]
