# Generated by Django 3.1.7 on 2021-04-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0028_remove_deudas_pagototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='promediodepago',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='totalapagar',
            field=models.IntegerField(null=True),
        ),
    ]
