# Generated by Django 3.1.7 on 2021-04-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0029_auto_20210403_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='promediodepago',
        ),
    ]
