# Generated by Django 3.1.7 on 2021-04-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0030_remove_deudas_promediodepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='totalapagar',
        ),
    ]
