# Generated by Django 3.1.7 on 2021-04-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0032_deudas_deudatotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='deudatotal',
        ),
    ]
