# Generated by Django 3.1.7 on 2021-04-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0034_auto_20210403_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasadelmes',
            name='PagoPromedio',
        ),
        migrations.AlterField(
            model_name='tasadelmes',
            name='Tabla',
            field=models.CharField(default=2021, max_length=10),
            preserve_default=False,
        ),
    ]
