# Generated by Django 3.1.7 on 2021-04-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0035_auto_20210403_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='deudadepago',
            field=models.IntegerField(null=True),
        ),
    ]
